### ISSUE TITLE
Multi-assign on prefixed variables does not work

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie_parser#58]
Or whatever the official term if for this kind of code:
```ruby
self.year, self.month, self.day = year, month, day
```
This generates a parse error in Natalie, but works with Ruby.

I found this when trying to see how much of the xmlrpc gem we could use by now.
 https://github.com/ruby/xmlrpc/blob/9f219e462793a5da3a2e30ad892e2c4482b8100c/lib/xmlrpc/datetime.rb#L85

**Comment by seven1m** [comment]
Archiving this repo in favor of YARP...
